import UIKit

// Ususally generated by swiftgen

extension UIImage {

    enum AssetIdentifier: String, CaseIterable {
        case mapMarker = "map_marker"
    }

    convenience init!(assetIdentifier: AssetIdentifier) {
        self.init(named: assetIdentifier.rawValue)
    }
}
